
DROP TABLE Lagerpflege			CASCADE;
DROP TABLE Terrariumpflege		CASCADE;
DROP TABLE Tierpflege			CASCADE;
DROP TABLE Futter				CASCADE;
DROP TABLE Verbrauch			CASCADE;
DROP TABLE Arbeitsdienste		CASCADE;
DROP TABLE Arbeitsdiensttypen	CASCADE;
DROP TABLE Wasserbecken			CASCADE;
DROP TABLE Bodenbelag			CASCADE;
DROP TABLE Deko					CASCADE;
DROP TABLE Pflanzen				CASCADE;
DROP TABLE Leuchtmittel			CASCADE;
DROP TABLE Verbrauchsmittel		CASCADE;
DROP TABLE Habitattypen			CASCADE;
DROP TABLE Terrarien			CASCADE;
DROP TABLE Tiere				CASCADE;
DROP TABLE Unterarten			CASCADE;
